name: Build PicoSmartFrame

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential git python3 python3-pip
          python3 -m pip install --upgrade pip

      - name: Clone Pico SDK with submodules
        run: |
          if [ ! -d "pico-sdk" ]; then
              git clone --recurse-submodules -b master https://github.com/raspberrypi/pico-sdk.git
          else
              cd pico-sdk
              git pull
              git submodule update --init --recursive
          fi

      - name: Build firmware
        run: |
          mkdir -p build
          cd build
          cmake -DPICO_SDK_PATH=../pico-sdk ..
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pico_smart_display
          path: |
              build/pico_smart_display.uf2
