name: Build PicoSmartFrame

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential git python3 python3-pip
          python3 -m pip install --upgrade pip

      - name: Clone Pico SDK with submodules
        run: |
          git submodule add https://github.com/raspberrypi/pico-sdk.git
          git submodule update --init

      - name: Build firmware
        run: |
          mkdir -p build
          cd build
          git submodule add https://github.com/raspberrypi/pico-sdk.git
          git submodule update --init
          cmake -DPICO_SDK_PATH=./pico-sdk ..
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pico_smart_display
          path: |
              build/pico_smart_display.elf
              build/pico_smart_display.uf2
